### ISSUE TITLE
Install scipt issue

### ISSUE THREAD

**Issue by bijanbina** [aliva/SubtitleFixer#1]
salam 
oon dastori ke baraye nasb gozashtid kharab hast 
chon beraye ejra kardan oon scripty ke download mi konad niaz be permission execute hast
in dastoor benazaram behtare

‍‍‍`wget https://github.com/aliva/SubtitleFixer/raw/master/install.sh
-O subtitlefixer-install.sh;sudo
chmod u+x;sudo ./subtitlefixer-install.sh`

albate bazam error mide

```
Cloning into 'SubtitleFixer'...
remote: Counting objects: 49, done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 49 (delta 15), reused 37 (delta 6)
Receiving objects: 100% (49/49), 8.50 KiB, done.
Resolving deltas: 100% (15/15), done.
./subtitlefixer-install.sh: 40: [: 0: unexpected operator
************************
subtitlefixer installed!
************************
```

**Comment by aliva** [comment]
سلام.

در صورتی که مشکل اجرا باشه کلا اسکریپت اجرا نمی‌شه. این ارور که گذاشتین از یک چیز دیگست.

خط ۴۰ اسکرپیت که اینه 

`if [ $? == 1 ]`

این مربوط به جایی می‌شه که
alias
به فایل 
bashrc
اضافه می‌شه.

نصب اسکرپت انجام شده فقط خط مربو بهش به فایل 
bashrc
اضافه نشده.

دلیل خطا رو نمی‌دونم. رو سیستم من که خطا نمی‌ده!
شاید شما از
zsh
استفاده می‌کنین؟

(اگه دلیل خطا رو نفهمیدیم این قسمت از اسکریپت رو کلا حذف می‌کنیم)

---

برای نصب هم چون از

`sh subtitle-install`

استفاده کردم نیازی به مجوز اجرای نداره ولی اگه فکر می‌کنین اونجوری بهتره اشکالی نداره تغییرش می‌دم.

**Comment by bijanbina** [comment]
mamnoon az pasokhet
darmorede zsh bayad begam ke roye systeme man nasb nist ama khob rahnaiie khobi bod
behtarin kar ine ke khat
#!/bin/bash
ra be avale file scriptet ezafe koni(in yek standard ya behtare begam prefix hast ta linux ba yek mofasere dorost scriptet ro run kone)
darbare script ham be nazaram chizi ke man gozashtam tamiz tare va vazeh tar ama belakhare tasmim ba shomast

baz ham mamnoon

**Comment by aliva** [comment]
تغییراتی که گفتین اعمال کردم. امید وارم مشکل حل شده باشه.

**Comment by bijanbina** [comment]
it works like a charm!!!!
