### ISSUE TITLE
مشکل در اجرا

### ISSUE THREAD

**Issue by odysseusjourney** [aliva/SubtitleFixer#2]
وقتی سعی می‌کنم اجرا کنم برنامه رو با این خطا مواجه می‌شم: 

```
$  ~/.local/bin/SubtitleFixer/SubtitleFixer /home/odysseus/Videos/Movie/Not\ Seen/Claude\ Chabrol/Les\ Biches\ \(1968\)\ /Les\ biches\ \(1968\).DVDversion.JiG.srt 
bash: /home/odysseus/.local/bin/SubtitleFixer/SubtitleFixer: /usr/bin/python2: bad interpreter: No such file or directory
```

**Comment by aliva** [comment]
این مشکل سز خط اول  برنامه یعنی 

```
#!/usr/bin/python2
```

ایجاد شده

خط اول باید دستوری باشه که پایتون۲ رو اجرا کنه و توی توزیع شما این دستور اجرا نمی‌شه
دستوری ندیدم که توی همه توزیع‌ها پایتون۲ رو اجرا کنه و دستور فعلی توی همه توزیعهای معمول فعلی جواب می‌ده

نظرم اینه که شما خط اول اسکریپت رو تغییر بدین که مشکل شما حل بشه

مثلا اگه شما پایتون۲.۷ رو نصب دارین خط اول برنامه رو به این صورت تغییر بدید

```
#!/usr/bin/python2.7
```

راه حل دوم هم اینه که یک فایل لینک بسازید یعنی بادستور

```
sudo ln -s /usr/bin/python2.7 /usr/bin/python2
```

فعلا راه حل بهتری به ذهنم نمی‌رسه. اگه پیشنهادی دارید ختما بگید

**Comment by odysseusjourney** [comment]
مرسی مرسی :)
جواب داد و داره کار می‌کنه
من اصلن با کد نویسی آشنا نیستم، ولی به ذهنم رسید که شاید بشه به یه نحوی، اسکریپت رو طوری تغییر بدین که به یک ورژن ِ خاص وابسته نباشه، مثلن: 
/usr/bin/python\* 
نمی‌دونم که چنین امکانی وجود داره یا خیر
موفق باشید 
(:

**Comment by aliva** [comment]
خط اول رو به

```
#!/usr/bin/python2.7
```

تغییر دادم
